### ISSUE TITLE
Document how to push multiple modules in Buf workspace

### ISSUE THREAD

**Issue by xmlking** [bufbuild/buf-push-action#22]
As Buf supports multi-module proto workspaces  as documented here https://docs.buf.build/tour/push-workspace-modules , 
please document how to push multiple modules via this GitHub action for a monorepo.

If possible, please improve this action to support pushing multi-module repo with coordinated  `buf mod update` and `buf push`

**Comment by amckinney** [comment]
This will largely depend on the modules defined in your workspace. In short, you'll need to push and update each module in the order of a DAG - the upstream modules should be pushed first, so that the downstream modules can update to the latest commit, be pushed themselves, and so on. This is described [here](https://docs.buf.build/reference/workspaces#pushing-modules).

A very crude example is something like this:
```yaml
steps:
  # Run `git checkout`
  - uses: actions/checkout@v2
  # Install the `buf` CLI
  - uses: bufbuild/buf-setup-action@v1
  - uses: bufbuild/buf-push-action@v1
    with:
      input: paymentapis
      buf_token: ${{ secrets.BUF_TOKEN }}
  - name: update-petapis
    run: buf mod update petapis
  - uses: bufbuild/buf-push-action@v1
    with:
      input: petapis
      buf_token: ${{ secrets.BUF_TOKEN }}
```

It's important to note that you should also check in the updated `petapis/buf.lock` file (from the `buf mod update petapis` command) so that it's committed back to your repository.

We'd eventually like to bake all this complexity into the `buf push` command itself - see [this issue](https://github.com/bufbuild/buf/issues/838) for details.
